# Colors (Everforest Dark Hard Contrast)

# Default colors
[colors.primary]
background = '#2b3339'
foreground = '#d3c6aa'

# Normal colors
[colors.normal]
black   = '#4b565c'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

# Bright colors
[colors.bright]
black   = '#859289'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'
