# Colors (Everforest Light Hard Contrast)

# Default colors
[colors.primary]
background = '#fff9e8'
foreground = '#5c6a72'

# Normal colors
[colors.normal]
black   = '#5c6a72'
red     = '#f85552'
green   = '#8da101'
yellow  = '#dfa000'
blue    = '#3a94c5'
magenta = '#df69ba'
cyan    = '#35a77c'
white   = '#939f91'

# Bright colors
[colors.bright]
black   = '#829181'
red     = '#f85552'
green   = '#8da101'
yellow  = '#dfa000'
blue    = '#3a94c5'
magenta = '#df69ba'
cyan    = '#35a77c'
white   = '#5c6a72'
